Beginnings of the revamp
TeamJeeves/Jeeves-Bot-Documentation pull request #15
Opened 2021-08-01 15:52 UTC by kieranjarrett

The starting of updating the documentation to Jeeves 4.0

2021-08-28 14:17 UTC, SirDeadlystrike requested changes

2021-08-28 14:17 UTC, SirDeadlystrike commented on docs/commands/dashboard/role-management.md
> +|Manual|This means that Jeeves will only apply roles when a player runs `!toon update`.|
This should be `!role update` not `!toon update`

2021-08-28 14:17 UTC, SirDeadlystrike commented on docs/commands/dashboard/role-management.md
> +|Auto|This means that Jeeves will apply the roles when a player runs `!auth`, when a player joins the server and has already run `!auth` on another server, or when a player runs `!toon update`.|
I would add some more clarification about auto vs manual.

EX:
Auto - Jeeves will where applicable automatically update roles for users on certain events. Such as....
- A user linking/updating their battlenet account via `!auth`
- A user forcing an update of their toons via `!toon update`
- Jeeves Premium Role Automation

Manual - Jeeves will only ever update a users roles if they run the `!role update` command in your server

2021-08-28 14:17 UTC, SirDeadlystrike commented on mkdocs.yml
> +    - Dashboard:
This should probably not be in the Command Scope but instead given a top level spot or put under a new "Configuring Jeeves" scope

2021-08-28 15:12 UTC, kieranjarrett commented on mkdocs.yml
> +    - Dashboard:
Shifted this in new commits. Looking at the guides menu, I think some could probably move into Configuration, some probably aren't needed any more, and then maybe a new menu for the Change log and the supporting Jeeves page?

2021-08-29 15:57 UTC, kieranjarrett commented
@SirDeadlystrike  Need you to take a look at the Supporting Jeeves page I just drafted.

2021-09-22 15:56 UTC, kieranjarrett commented
@SirDeadlystrike Do you prefer the written permissions style or the table?

2021-10-02 19:46 UTC, akintis008 approved these changes

2021-10-02 19:47 UTC, SirDeadlystrike approved these changes

2021-10-02 19:47 UTC, merged