Doc Changes
TeamJeeves/Jeeves-Bot-Documentation pull request #18
Opened 2023-03-21 01:58 UTC by Riot1138

I removed some outdated things like Jeeves News. Moved Reaction Role commands section to Tools. Included information on the Role-tools commands. Added screenshots where it might be nice to see how things works IE feeds. Added screenshots where there was a note to add a screenshot. Added information of how to restrict commands via Discord and removed the info of it being on the Dashboard. Removed any mention of a prefix. Added a brief snippet of Jeeves's uses on the front page beneath Welcome to Jeeves. Deleted the 3.0 Update info on that page. Me realizing I forgot to update the Guild part under Configuration. I'll get to that later. Added a specific snippet that "Verified" role isn't related to Guild or other integrations, just that they are authorized with Jeeves. Added a note for Role Management "Guild" that it is where you turn on/off the function, not where you assign roles to rank.

2023-03-21 04:34 UTC, SirDeadlystrike requested changes

2023-03-21 04:34 UTC, SirDeadlystrike commented on docs/img/characters-view.PNG
Can we get a non-squished version of this please. 
The formatting should display properly on 1080p 1440p and 4K screens or well any desktop screen (sorry mobile users)

2023-03-21 04:34 UTC, SirDeadlystrike commented on docs/configuration/role-management/verified.md
> +The Verified integration assigns the 'Verified' role to all users that have linked their discord account to a battle.net account via `/authorize`. This is **not** a role related to any other integrat
> This is **not** a role related to any other integration 

This wording confuses me, I am not sure what it is trying to convey.

2023-03-21 04:34 UTC, SirDeadlystrike commented on docs/configuration/Command Control.md
> +This section doesn't exist on the Dashboard anymore as Discord has its own way to limit commands for users/roles via their interface. Navigate to your Discord Server Settings and find `Integrations`
This still exists, but is depreciated. I don't think the removal is going to be ultra-soon.

I think it would be more honest to say something to the tune of "You can use Discords Integration menu in your server to restrict the bot as a whole and even specific commands to users/roles/channels of your choice. Jeeves has legacy support to do this via our web dashboard but this is considered depricated and will be removed in the future. Please use Discords Integration page to setup your command restrictions"

2023-03-21 04:34 UTC, SirDeadlystrike commented on docs/commands/warcraft/character.md
> +Type `/characters view` to use this feature. This will show a list of all your max level characters, if you have none max level, the view command will display as blank like below. You can also specif
I would make this part extra clear.

When viewing your own character, the posted list is private and only visible to you. 
When viewing someone else's character, the posted list of public and visible to all members in the channel.

2023-03-24 22:19 UTC, Riot1138 commented on docs/configuration/role-management/verified.md
> +The Verified integration assigns the 'Verified' role to all users that have linked their discord account to a battle.net account via `/authorize`. This is **not** a role related to any other integrat
People have thought the verified role means they're part of the guild.

2023-03-24 22:46 UTC, Riot1138 commented on docs/img/characters-view.PNG
I think I was able to fix? I'm not sure what you mean by squished as it appears fine on my end. I resized to make it bigger but I'm restricted to snipping tool and MSpaint.
![characters-view](https://user-images.githubusercontent.com/123217321/227656487-009f47c9-7064-412b-b4d7-77c72fa47ad1.PNG)

2023-03-24 22:51 UTC, Riot1138 commented on docs/configuration/role-management/verified.md
> +The Verified integration assigns the 'Verified' role to all users that have linked their discord account to a battle.net account via `/authorize`. This is **not** a role related to any other integrat
I reworded just to restate what it is.

2023-04-24 05:14 UTC, SirDeadlystrike approved these changes

2023-04-24 05:14 UTC, merged